name: HyperVS_Auto_Build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'OTA Url'
        required: false
        default: ''
      vip:
        type: boolean
        description: Vietsub Pro
        default: true
      stock:
        type: boolean
        description: Build Stock fastboot Rom
        default: false
      custom:
        type: boolean
        description: Custom branch
        default: false
      key:
        description: 'Active Key'
        required: true
        default: ''

jobs:
  EvaluateCondition:
    runs-on: ubuntu-latest
    outputs:
      condition-result: ${{ steps.evaluate.outputs.condition-result }}
    steps:
      - name: Evaluate condition
        id: evaluate
        run: echo "::set-output name=condition-result::${{ github.event.inputs.key != secrets.AUTH_KEY }}"

  Build:
    needs: EvaluateCondition
    if: ${{ needs.EvaluateCondition.outputs.condition-result == 'true' }}
    runs-on: ubuntu-latest
    environment: AutoBuild
    steps:
      - name: TEST
        run: echo "::set-output name=condition-result::${{ github.event.inputs.key != secrets.AUTH_KEY }}"
