name: HyperVS_Auto_Build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'OTA Url'
        required: false
        default: ''
      vip:
        type: boolean
        description: Vietsub Pro
        default: true
      stock:
        type: boolean
        description: Build Stock fastboot Rom
        default: false
      custom:
        type: boolean
        description: Custom branch
        default: false
      key:
        description: 'Active Key'
        required: true
        default: ''

jobs:
  BuildAuthorizedKey:
    if: ${{ github.event.inputs.key == secrets.AUTH_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps as needed for the build process

  BuildUnauthorizedKey:
    if: ${{ github.event.inputs.key != secrets.AUTH_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify user of unauthorized access
        run: |
           echo ${{ vars.AUTH_KEY }}
           echo ${{ github.event.inputs.key }}
           echo ${{ github.event.inputs.key != vars.AUTH_KEY }}
        

      # Add more steps or actions as needed for handling unauthorized access
