name: Hyper_VS_Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: buihien224/vietsub_erofs_tool
          token: ${{ secrets.CLONE_KEY }}
