name: Hyper_VS_Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    environment: AutoBuild
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.CLONE_KEY }}
          repository: buihien224/vietsub_erofs_tool
